/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 ../../assets/Carpincho3D.gltf -T -t -o Carpincho3D
*/

/*
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    cube: THREE.Mesh
    cube_1: THREE.Mesh
    cube_2: THREE.Mesh
    cube_3: THREE.Mesh
    cube_4: THREE.Mesh
    cube_5: THREE.Mesh
    cube_6: THREE.Mesh
    cube_7: THREE.Mesh
    cube_8: THREE.Mesh
    cube_9: THREE.Mesh
    cube_10: THREE.Mesh
    cube_11: THREE.Mesh
    cube_12: THREE.Mesh
    cube_13: THREE.Mesh
    cube_14: THREE.Mesh
    cube_15: THREE.Mesh
    cube_16: THREE.Mesh
    cube_17: THREE.Mesh
    cube_18: THREE.Mesh
    cube_19: THREE.Mesh
    cube_20: THREE.Mesh
    cube_21: THREE.Mesh
    cube_22: THREE.Mesh
    cube_23: THREE.Mesh
    cube_24: THREE.Mesh
    cube_25: THREE.Mesh
    cube_26: THREE.Mesh
    cube_27: THREE.Mesh
    cube_28: THREE.Mesh
    cube_29: THREE.Mesh
    cube_30: THREE.Mesh
    cube_31: THREE.Mesh
    cube_32: THREE.Mesh
    cube_33: THREE.Mesh
    cube_34: THREE.Mesh
    cube_35: THREE.Mesh
    cube_36: THREE.Mesh
    cube_37: THREE.Mesh
    cube_38: THREE.Mesh
    cube_39: THREE.Mesh
    cube_40: THREE.Mesh
    cube_41: THREE.Mesh
    cube_42: THREE.Mesh
    cube_43: THREE.Mesh
    cube_44: THREE.Mesh
    cube_45: THREE.Mesh
    cube_46: THREE.Mesh
    cube_48: THREE.Mesh
cube_47: THREE.Mesh
    cube_49: THREE.Mesh
    cube_50: THREE.Mesh
    cube_51: THREE.Mesh
  }
  materials: {}
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/Carpincho3D.gltf') as unknown as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[-0.25, 1.75, 0]}>
        <mesh geometry={nodes.cube_7.geometry} material={nodes.cube_7.material} position={[-0.14, -0.72, -0.49]} rotation={[0, -0.17, 0]} />
        <mesh geometry={nodes.cube_8.geometry} material={nodes.cube_8.material} position={[0.25, -2, 0]} />
        <mesh geometry={nodes.cube_9.geometry} material={nodes.cube_9.material} position={[0.25, -2, 0]} />
        <mesh geometry={nodes.cube_10.geometry} material={nodes.cube_10.material} position={[0.25, -2, 0]} />
        <mesh geometry={nodes.cube_11.geometry} material={nodes.cube_11.material} position={[0.25, -2, 0]} />
        <mesh geometry={nodes.cube_12.geometry} material={nodes.cube_12.material} position={[0.25, -2, 0]} />
        <mesh geometry={nodes.cube_13.geometry} material={nodes.cube_13.material} position={[0.16, -1.19, 0]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.cube_14.geometry} material={nodes.cube_14.material} position={[0.16, -1.19, 0]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.cube_15.geometry} material={nodes.cube_15.material} position={[0.25, -2, 0]} />
        <mesh geometry={nodes.cube_16.geometry} material={nodes.cube_16.material} position={[0.25, -1.75, 0]} />
        <mesh geometry={nodes.cube_17.geometry} material={nodes.cube_17.material} position={[0.25, -1.75, 0]} />
        <mesh geometry={nodes.cube_18.geometry} material={nodes.cube_18.material} position={[0.25, -1.75, 0]} rotation={[0, 0.09, 0]} />
        <mesh geometry={nodes.cube_19.geometry} material={nodes.cube_19.material} position={[0.59, -0.72, -0.29]} rotation={[0, 0.17, Math.PI]} />
        <mesh geometry={nodes.cube_20.geometry} material={nodes.cube_20.material} position={[0.59, -0.72, -0.29]} rotation={[0, -0.09, Math.PI]} />
        <mesh geometry={nodes.cube_21.geometry} material={nodes.cube_21.material} position={[0.44, 0, 0]} rotation={[0, 0, -Math.PI / 6]} />
        <mesh geometry={nodes.cube_22.geometry} material={nodes.cube_22.material} rotation={[0, 0, 0.48]} />
        <mesh geometry={nodes.cube_23.geometry} material={nodes.cube_23.material} rotation={[0, 0, 0.48]} />
        <mesh geometry={nodes.cube_24.geometry} material={nodes.cube_24.material} position={[0.25, -1.75, 0]} />
        <mesh geometry={nodes.cube_25.geometry} material={nodes.cube_25.material} position={[0.44, 0, 0.01]} rotation={[0, 0, -0.48]} />
        <mesh geometry={nodes.cube_26.geometry} material={nodes.cube_26.material} position={[0.25, -1.75, 0]} />
        <mesh geometry={nodes.cube_27.geometry} material={nodes.cube_27.material} position={[0.25, -1.75, 0]} />
        <mesh geometry={nodes.cube_28.geometry} material={nodes.cube_28.material} position={[0.25, -1.75, 0]} />
        <mesh geometry={nodes.cube_29.geometry} material={nodes.cube_29.material} position={[0.25, -1.75, 0]} />
      </group>
      <group position={[-0.05, 1.97, 0]}>
        <mesh geometry={nodes.cube_30.geometry} material={nodes.cube_30.material} position={[0.05, -1.97, 0]} />
        <mesh geometry={nodes.cube_31.geometry} material={nodes.cube_31.material} position={[0.05, -0.03, 0]} rotation={[0, 0, -0.09]} />
        <mesh geometry={nodes.cube_32.geometry} material={nodes.cube_32.material} rotation={[0, 0, Math.PI / 8]} />
      </group>
      <group position={[0.66, 1.05, -0.81]} rotation={[0, -Math.PI / 6, 0]}>
        <mesh geometry={nodes.cube_33.geometry} material={nodes.cube_33.material} position={[-0.5, -1.08, 1.38]} />
        <mesh geometry={nodes.cube_34.geometry} material={nodes.cube_34.material} position={[0, -0.09, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
        <mesh geometry={nodes.cube_35.geometry} material={nodes.cube_35.material} position={[-0.5, -1.08, 1.38]} />
        <mesh geometry={nodes.cube_36.geometry} material={nodes.cube_36.material} position={[0.06, -0.06, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.cube_37.geometry} material={nodes.cube_37.material} position={[0.06, -0.06, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.cube_38.geometry} material={nodes.cube_38.material} position={[0.06, -0.06, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.cube_39.geometry} material={nodes.cube_39.material} position={[0.06, -0.06, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.cube_40.geometry} material={nodes.cube_40.material} position={[0, -0.06, 0]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.cube_41.geometry} material={nodes.cube_41.material} position={[0, -0.06, 0]} rotation={[Math.PI / 8, 0, Math.PI / 2]} />
        <mesh geometry={nodes.cube_42.geometry} material={nodes.cube_42.material} position={[0, -0.06, 0]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.cube_43.geometry} material={nodes.cube_43.material} position={[0, -0.06, 0]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.cube_44.geometry} material={nodes.cube_44.material} position={[0.13, -0.06, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.cube_45.geometry} material={nodes.cube_45.material} position={[0.13, -0.06, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.cube_46.geometry} material={nodes.cube_46.material} position={[0.06, -0.06, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.cube_47.geometry} material={nodes.cube_47.material} position={[0, -0.09, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
        <mesh geometry={nodes.cube_48.geometry} material={nodes.cube_48.material} position={[0.06, 0.03, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.cube_49.geometry} material={nodes.cube_49.material} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
        <mesh geometry={nodes.cube_50.geometry} material={nodes.cube_50.material} position={[0.06, 0.03, 0]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.cube_51.geometry} material={nodes.cube_51.material} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
      </group>
      <mesh geometry={nodes.cube.geometry} material={nodes.cube.material} />
      <mesh geometry={nodes.cube_1.geometry} material={nodes.cube_1.material} position={[-0.03, 0.91, -1.19]} rotation={[1.09, 0, 0]} />
      <mesh geometry={nodes.cube_2.geometry} material={nodes.cube_2.material} />
      <mesh geometry={nodes.cube_3.geometry} material={nodes.cube_3.material} />
      <mesh geometry={nodes.cube_4.geometry} material={nodes.cube_4.material} />
      <mesh geometry={nodes.cube_5.geometry} material={nodes.cube_5.material} />
      <mesh geometry={nodes.cube_6.geometry} material={nodes.cube_6.material} />
    </group>
  )
}

useGLTF.preload('/Carpincho3D-transformed.glb')
*/
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    cube: THREE.Mesh;
    cube_1: THREE.Mesh;
    cube_2: THREE.Mesh;
    cube_3: THREE.Mesh;
    cube_4: THREE.Mesh;
    cube_5: THREE.Mesh;
    cube_6: THREE.Mesh;
    cube_7: THREE.Mesh;
    cube_8: THREE.Mesh;
    cube_9: THREE.Mesh;
    cube_10: THREE.Mesh;
    cube_11: THREE.Mesh;
    cube_12: THREE.Mesh;
    cube_13: THREE.Mesh;
    cube_14: THREE.Mesh;
    cube_15: THREE.Mesh;
    cube_16: THREE.Mesh;
    cube_17: THREE.Mesh;
    cube_18: THREE.Mesh;
    cube_19: THREE.Mesh;
    cube_20: THREE.Mesh;
    cube_21: THREE.Mesh;
    cube_22: THREE.Mesh;
    cube_23: THREE.Mesh;
    cube_24: THREE.Mesh;
    cube_25: THREE.Mesh;
    cube_26: THREE.Mesh;
    cube_27: THREE.Mesh;
    cube_28: THREE.Mesh;
    cube_29: THREE.Mesh;
    cube_30: THREE.Mesh;
    cube_31: THREE.Mesh;
    cube_32: THREE.Mesh;
    cube_33: THREE.Mesh;
    cube_34: THREE.Mesh;
    cube_35: THREE.Mesh;
    cube_36: THREE.Mesh;
    cube_37: THREE.Mesh;
    cube_38: THREE.Mesh;
    cube_39: THREE.Mesh;
    cube_40: THREE.Mesh;
    cube_41: THREE.Mesh;
    cube_42: THREE.Mesh;
    cube_43: THREE.Mesh;
    cube_44: THREE.Mesh;
    cube_45: THREE.Mesh;
    cube_46: THREE.Mesh;
    cube_47: THREE.Mesh;
    cube_48: THREE.Mesh;
    cube_49: THREE.Mesh;
    cube_50: THREE.Mesh;
    cube_51: THREE.Mesh;
    cube_52: THREE.Mesh;
    cube_53: THREE.Mesh;
  };
  materials: {};
};


export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/modelConMate.gltf") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[-0.25, 1.75, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_7.geometry}
          material={nodes.cube_7.material}
          position={[-0.141139, -0.71875, -0.489782]}
          rotation={[0, -0.174533, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_8.geometry}
          material={nodes.cube_8.material}
          position={[0.25, -2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_9.geometry}
          material={nodes.cube_9.material}
          position={[0.25, -2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_10.geometry}
          material={nodes.cube_10.material}
          position={[0.25, -2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_11.geometry}
          material={nodes.cube_11.material}
          position={[0.25, -2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_12.geometry}
          material={nodes.cube_12.material}
          position={[0.25, -2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_13.geometry}
          material={nodes.cube_13.material}
          position={[0.15625, -1.1875, 0]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_14.geometry}
          material={nodes.cube_14.material}
          position={[0.15625, -1.1875, 0]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_15.geometry}
          material={nodes.cube_15.material}
          position={[0.25, -2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_16.geometry}
          material={nodes.cube_16.material}
          position={[0.25, -1.75, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_17.geometry}
          material={nodes.cube_17.material}
          position={[0.25, -1.75, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_18.geometry}
          material={nodes.cube_18.material}
          position={[0.25, -1.75, 0]}
          rotation={[0, 0.087266, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_19.geometry}
          material={nodes.cube_19.material}
          position={[0.588938, -0.71875, -0.290806]}
          rotation={[0, 0.174533, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_20.geometry}
          material={nodes.cube_20.material}
          position={[0.588938, -0.71875, -0.290806]}
          rotation={[0, -0.087266, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_21.geometry}
          material={nodes.cube_21.material}
          position={[0.4375, 0, 0]}
          rotation={[0, 0, -Math.PI / 6]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_22.geometry}
          material={nodes.cube_22.material}
          rotation={[0, 0, 0.479966]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_23.geometry}
          material={nodes.cube_23.material}
          rotation={[0, 0, 0.479966]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_24.geometry}
          material={nodes.cube_24.material}
          position={[0.25, -1.75, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_25.geometry}
          material={nodes.cube_25.material}
          position={[0.4375, 0, 0.007813]}
          rotation={[0, 0, -0.479966]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_26.geometry}
          material={nodes.cube_26.material}
          position={[0.25, -1.75, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_27.geometry}
          material={nodes.cube_27.material}
          position={[0.25, -1.75, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_28.geometry}
          material={nodes.cube_28.material}
          position={[0.25, -1.75, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_29.geometry}
          material={nodes.cube_29.material}
          position={[0.25, -1.75, 0]}
        />
      </group>
      <group position={[-0.046875, 1.96875, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_30.geometry}
          material={nodes.cube_30.material}
          position={[0.046875, -1.96875, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_31.geometry}
          material={nodes.cube_31.material}
          position={[0.046875, -0.03125, 0]}
          rotation={[0, 0, -0.087266]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_32.geometry}
          material={nodes.cube_32.material}
          rotation={[0, 0, Math.PI / 8]}
        />
      </group>
      <group
        position={[0.65625, 1.040625, -0.8125]}
        rotation={[0, -Math.PI / 6, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_33.geometry}
          material={nodes.cube_33.material}
          position={[-0.5, -1.078125, 1.375]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_34.geometry}
          material={nodes.cube_34.material}
          position={[0.0625, -0.0625, 0]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_35.geometry}
          material={nodes.cube_35.material}
          position={[0.0625, -0.0625, 0]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_36.geometry}
          material={nodes.cube_36.material}
          position={[0, -0.09375, 0]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_37.geometry}
          material={nodes.cube_37.material}
          position={[0, -0.09375, 0]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_38.geometry}
          material={nodes.cube_38.material}
          position={[0.0625, -0.0625, 0]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_39.geometry}
          material={nodes.cube_39.material}
          position={[0.125, -0.0625, 0]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_40.geometry}
          material={nodes.cube_40.material}
          position={[0.0625, -0.0625, 0]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_41.geometry}
          material={nodes.cube_41.material}
          position={[0.0625, -0.0625, 0]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_42.geometry}
          material={nodes.cube_42.material}
          position={[0.125, -0.0625, 0]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_43.geometry}
          material={nodes.cube_43.material}
          position={[0, -0.0625, 0]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_44.geometry}
          material={nodes.cube_44.material}
          position={[0, -0.0625, 0]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_45.geometry}
          material={nodes.cube_45.material}
          position={[0, -0.0625, 0]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_46.geometry}
          material={nodes.cube_46.material}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_47.geometry}
          material={nodes.cube_47.material}
          position={[0.0625, 0.03125, 0]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_48.geometry}
          material={nodes.cube_48.material}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_49.geometry}
          material={nodes.cube_49.material}
          position={[0.0625, 0.03125, 0]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_50.geometry}
          material={nodes.cube_50.material}
          position={[-0.5, -1.078125, 1.375]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_51.geometry}
          material={nodes.cube_51.material}
          position={[0, -0.0625, 0]}
          rotation={[Math.PI / 8, 0, Math.PI / 2]}
        />
      </group>
      <group rotation={[0, -0.087266, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_52.geometry}
          material={nodes.cube_52.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cube_53.geometry}
          material={nodes.cube_53.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube.geometry}
        material={nodes.cube.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_1.geometry}
        material={nodes.cube_1.material}
        position={[-0.03125, 0.90625, -1.1875]}
        rotation={[1.090831, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_2.geometry}
        material={nodes.cube_2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_3.geometry}
        material={nodes.cube_3.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_4.geometry}
        material={nodes.cube_4.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_5.geometry}
        material={nodes.cube_5.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_6.geometry}
        material={nodes.cube_6.material}
      />
    </group>
  );
}

useGLTF.preload("/modelConMate.gltf");
