/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 ../../assets/Carpincho3D.gltf -T -t -o Carpincho3D
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    cube: THREE.Mesh
    cube_1: THREE.Mesh
    cube_2: THREE.Mesh
    cube_3: THREE.Mesh
    cube_4: THREE.Mesh
    cube_5: THREE.Mesh
    cube_6: THREE.Mesh
    cube_7: THREE.Mesh
    cube_8: THREE.Mesh
    cube_9: THREE.Mesh
    cube_10: THREE.Mesh
    cube_11: THREE.Mesh
    cube_12: THREE.Mesh
    cube_13: THREE.Mesh
    cube_14: THREE.Mesh
    cube_15: THREE.Mesh
    cube_16: THREE.Mesh
    cube_17: THREE.Mesh
    cube_18: THREE.Mesh
    cube_19: THREE.Mesh
    cube_20: THREE.Mesh
    cube_21: THREE.Mesh
    cube_22: THREE.Mesh
    cube_23: THREE.Mesh
    cube_24: THREE.Mesh
    cube_25: THREE.Mesh
    cube_26: THREE.Mesh
    cube_27: THREE.Mesh
    cube_28: THREE.Mesh
    cube_29: THREE.Mesh
    cube_30: THREE.Mesh
    cube_31: THREE.Mesh
    cube_32: THREE.Mesh
    cube_33: THREE.Mesh
    cube_34: THREE.Mesh
    cube_35: THREE.Mesh
    cube_36: THREE.Mesh
    cube_37: THREE.Mesh
    cube_38: THREE.Mesh
  }
  materials: {}
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/Carpincho3D-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.73, 1.01, -0.75]} rotation={[0, -0.57, 0]}>
        <mesh geometry={nodes.cube.geometry} material={nodes.cube.material} position={[-0.73, -1.01, 0.75]} />
        <mesh geometry={nodes.cube_1.geometry} material={nodes.cube_1.material} position={[-0.73, -1.01, 0.75]} />
        <mesh geometry={nodes.cube_2.geometry} material={nodes.cube_2.material} position={[-0.12, 0.06, 0]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.cube_3.geometry} material={nodes.cube_3.material} position={[-0.73, -1.01, 0.75]} />
        <mesh geometry={nodes.cube_4.geometry} material={nodes.cube_4.material} position={[-0.12, 0.06, 0]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.cube_5.geometry} material={nodes.cube_5.material} position={[-0.73, -1.01, 0.75]} />
        <mesh geometry={nodes.cube_6.geometry} material={nodes.cube_6.material} position={[0.12, -0.05, 0]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.cube_7.geometry} material={nodes.cube_7.material} position={[-0.73, -1.01, 0.75]} />
        <mesh geometry={nodes.cube_8.geometry} material={nodes.cube_8.material} position={[-0.73, -1.01, 0.75]} />
      </group>
      <group position={[-0.25, 1.75, 0]}>
        <mesh geometry={nodes.cube_16.geometry} material={nodes.cube_16.material} position={[0.25, -2, 0]} />
        <mesh geometry={nodes.cube_17.geometry} material={nodes.cube_17.material} position={[0.25, -2, 0]} />
        <mesh geometry={nodes.cube_18.geometry} material={nodes.cube_18.material} position={[0.25, -2, 0]} />
        <mesh geometry={nodes.cube_19.geometry} material={nodes.cube_19.material} position={[0.25, -2, 0]} />
        <mesh geometry={nodes.cube_20.geometry} material={nodes.cube_20.material} position={[0.25, -2, 0]} />
        <mesh geometry={nodes.cube_21.geometry} material={nodes.cube_21.material} position={[0.16, -1.19, 0]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.cube_22.geometry} material={nodes.cube_22.material} position={[0.25, -2, 0]} />
        <mesh geometry={nodes.cube_23.geometry} material={nodes.cube_23.material} position={[0.25, -1.75, 0]} />
        <mesh geometry={nodes.cube_24.geometry} material={nodes.cube_24.material} position={[0.25, -1.75, 0]} />
        <mesh geometry={nodes.cube_25.geometry} material={nodes.cube_25.material} position={[0.25, -1.75, 0]} rotation={[0, 0.09, 0]} />
        <mesh geometry={nodes.cube_26.geometry} material={nodes.cube_26.material} position={[0.44, 0, 0]} rotation={[0, 0, -Math.PI / 6]} />
        <mesh geometry={nodes.cube_27.geometry} material={nodes.cube_27.material} rotation={[0, 0, 0.48]} />
        <mesh geometry={nodes.cube_28.geometry} material={nodes.cube_28.material} position={[-0.14, -0.72, -0.49]} rotation={[0, -0.17, 0]} />
        <mesh geometry={nodes.cube_29.geometry} material={nodes.cube_29.material} position={[0.59, -0.72, -0.29]} rotation={[0, -0.09, Math.PI]} />
        <mesh geometry={nodes.cube_30.geometry} material={nodes.cube_30.material} position={[0.59, -0.72, -0.29]} rotation={[0, 0.17, Math.PI]} />
        <mesh geometry={nodes.cube_31.geometry} material={nodes.cube_31.material} position={[0.16, -1.19, 0]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.cube_32.geometry} material={nodes.cube_32.material} position={[0.25, -1.75, 0]} />
        <mesh geometry={nodes.cube_33.geometry} material={nodes.cube_33.material} position={[0.25, -1.75, 0]} />
        <mesh geometry={nodes.cube_34.geometry} material={nodes.cube_34.material} position={[0.25, -1.75, 0]} />
        <mesh geometry={nodes.cube_35.geometry} material={nodes.cube_35.material} position={[0.25, -1.75, 0]} />
        <mesh geometry={nodes.cube_36.geometry} material={nodes.cube_36.material} position={[0.25, -1.75, 0]} />
        <mesh geometry={nodes.cube_37.geometry} material={nodes.cube_37.material} rotation={[0, 0, 0.48]} />
        <mesh geometry={nodes.cube_38.geometry} material={nodes.cube_38.material} position={[0.44, 0, 0.01]} rotation={[0, 0, -0.48]} />
      </group>
      <mesh geometry={nodes.cube_9.geometry} material={nodes.cube_9.material} />
      <mesh geometry={nodes.cube_10.geometry} material={nodes.cube_10.material} position={[-0.03, 0.91, -1.19]} rotation={[1.09, 0, 0]} />
      <mesh geometry={nodes.cube_11.geometry} material={nodes.cube_11.material} />
      <mesh geometry={nodes.cube_12.geometry} material={nodes.cube_12.material} />
      <mesh geometry={nodes.cube_13.geometry} material={nodes.cube_13.material} />
      <mesh geometry={nodes.cube_14.geometry} material={nodes.cube_14.material} />
      <mesh geometry={nodes.cube_15.geometry} material={nodes.cube_15.material} />
    </group>
  )
}

useGLTF.preload('/Carpincho3D-transformed.glb')
